matrix:
  include:
    - os: linux
      dist: trusty
      env: CURRENTOS=UNDER_LINUX
      mono: latest
    - os: osx
      osx_image: xcode7.1
      env: CURRENTOS=UNDER_MACOSX
      mono: none
script:
  # installing .NET Core SDK
  - wget --retry-connrefused --waitretry=1 https://dot.net/v1/dotnet-install.sh
  - chmod +x dotnet-install.sh
  - if [[ $CURRENTOS == "UNDER_LINUX" ]]; then sudo apt-get install apt-transport-https libunwind8; fi
  - ./dotnet-install.sh --channel 3.1
  - export PATH="$PATH:$HOME/.dotnet"

  # run tests under .NET Core 3.1
  - dotnet test _Src/Tests/Tests.csproj -f netcoreapp3.1