version: 1.0.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '1.0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
skip_tags: true
clone_folder: c:\projects\simple-container
platform:
  - Any CPU
configuration:
  - Debug
  - Release
init:
  - git config --global core.autocrlf true
before_build:
  - nuget install NUnit.ConsoleRunner -Version 3.8.0
  - nuget install NUnit3TestAdapter -Version 3.9.0
  - copy /y NUnit.ConsoleRunner.3.8.0\tools\*.* c:\Tools\NUnit3
build_script:
  - dotnet build _Src\SimpleContainer.sln
test_script:
  - nunit3-console.exe "_Src\Tests\bin\%configuration%\net45\SimpleContainer.Tests.dll"
  - dotnet test "_Src\Tests\Tests.csproj" --no-restore --no-build -f netcoreapp2.0 -o "bin\%configuration%\netcoreapp2.0"
artifacts:
  - path: bin\$(configuration)\*.*