version: 1.0.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '1.0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
skip_tags: true
clone_folder: c:\projects\simple-container
platform:
  - Any CPU
configuration:
  - Debug
  - Release
init:
  - git config --global core.autocrlf true
before_build:
  - nuget restore _Src\SimpleContainer.sln
build:
  verbosity: minimal
  project: _Src\SimpleContainer.sln
test:
  assemblies:
    - '**\*.tests.dll'
artifacts:
  - path: bin\$(configuration)\*.*